### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by desmando**
Added instructions for Red Hat 7 (verified on rhel7.8)

### CODE REVIEW

**Comment by infrastation** [comment]
Thank you for proposing this contribution, let me provide some feedback.
* There is no such thing as "Red Hat 7", it would be much better to say exactly what you mean, that is, "RHEL 7".
* PHP 5.6 is very old, is it really the most recent version available on RHEL 7?
* RHEL 7 must have an Apache httpd package of its own, and as far as I used to think, a native package would never use `/opt/rh/httpd24/root/`, could you confirm?

**Comment by desmando** [comment]
Very good point on RHEL vs Red Hat.
PHP 7 is available as well, but I didn't want to jump that many full versions when racktables calls for 5.5 at least.
RHEL 7 does have an Apache httpd package that is where one would expect it. The reason that the path is supplied as /opt/rh/httpd24/root/ is that the php package in the standard RedHat repos maxes out at 5.4. So my instructions have you enabling the rhel-server-rhscl-7-rpms repo which is still a RedHat official repo but designed for people that need higher revision levels for programming. Those packages are linked to httpd24 only which puts its content in the /opt/rh/httpd24/root/ path.

**Comment by infrastation** [comment]
Re PHP versions, RackTables 0.21.x had been tested on PHP up to 7.3. RackTables 0.22.x will not work on PHP less than 7.0. So whatever is the stable supported PHP 7 version on RHEL 7, it would be the right version for the last release (0.21.3) and the next release (0.22.0) of RackTables.

Re installation paths, if you are sure that's the right location, I will take your word.

**Comment by desmando** [comment]
Let me withdraw this merge request then and redo it with PHP 7.

**Comment by infrastation** [comment]
If you do not feel confident with git rebase, just add more commits here and once the end result looks OK I will squash it all into one commit.

**Comment by desmando** [comment]
Changes made.

**Comment by infrastation** [comment]
Thank you!

**Pull request merged**
