### PR TITLE
Allow webfonts through CSS

### PR DESCRIPTION
**Pull request by netniV**
This pull request permits the use of webfonts through the addCSS/addJS functionality.  This also allows the use of font awesome once modified to use the `?index.php?module=chrome&uri=path/to/webfont` if you want to use a local version.

### CODE REVIEW

**Comment by infrastation** [comment]
Looks good except `CODE_VERSION` must be left intact in the scope of this change.

**Comment by netniV** [comment]
Did I include the CODE_VERSION? I must have added -a to my commit.

**Comment by netniV** [comment]
Should be sorted now.  Had to increase the code version to get the upgrade to work properly.

**Comment by infrastation** [comment]
Thank you!

**Pull request merged**
