### PR TITLE
Added ObjectParentCompat entry for UCS

### PR DESCRIPTION
**Pull request by bpothier**
Added entry for "Server"(4) to be member of "Management interface"(1787) in ObjectParentCompat.
This is to support standalone (rackmount) UCS servers that do not live inside a "Server chassis"(1502) to be directly associated.
Otherwise causes SQL violation when trying to linkEntity.
Will likely also need an entry in upgrade.php, like in 0.20.8 section:
// add rules for Cisco UCS objects
$query[] = "INSERT INTO `ObjectParentCompat` (`parent_objtype_id`, `child_objtype_id`) VALUES (1787,8),(1787,1502)";
but using "(1787,4)"?

### CODE REVIEW

**Comment by infrastation** [comment]
`upgrade.php` and `init-sample-racks.sql` need the same changes, do you want to make them yourself?

**Comment by bpothier** [comment]
There was no existing section (at the time) for upgrade, and you are better experienced with nuances of updating those :)

**Comment by infrastation** [comment]
Oops, lost the commit comment during the squash, sorry.

**Comment by infrastation** [comment]
I have left `init-sample-racks.sql` alone as the pre-release procedure should include this change together with other pending changes. Thank you!

**Pull request merged**
