### PR TITLE
Quick fix of formatting.

### PR DESCRIPTION
**Pull request by MichaelTiernan**
Made a couple of quick changes as I prepare to add to the docs. Fixed spacing and wrapping.

### CODE REVIEW

**Comment by MichaelTiernan** [comment]
Grr... My own stupid mistakes. Sorry.

**Comment by infrastation** [comment]
Thank you!

**Comment by MichaelTiernan** [comment]
Thanks @infrastation 

Okay, I'm still learning...

For my own education as well as those who may come along afterwards... why would I want to delete my fork of RT/rt? (I'm sure there's a logical reason you said that but _I_ am still learning the ins and outs of github.

**Comment by infrastation** [comment]
You deleted a branch, not the whole fork. When a branch is intended as temporary one-off buffer, that's a usual practice to delete it after merging.

**Pull request merged**
