### PR TITLE
add jquery ui autocomplete to object ip tab ( Allocations )

### PR DESCRIPTION
**Pull request by github138**
lists object port names as OS Interface
and suggests next ipv4 bytes for IP Address

* renderIPForObject (): add autocomplete
* getAutocompleteListAJAX (): add realms "bond_name" and "ip"

### CODE REVIEW

**Comment by andriyanov** [comment]
Autocomplete for port names seems a good idea to me.
But I'm not sure about IP addresses. Could you please explain the logic behind IP suggest?

**Comment by github138** [comment]
I did not suggest the whole net because e.g. it would suggest all 10.[0-255].0.0/24 nets if "10" is entered. So nets starting with 101..109 are just out of sight. Instead it just suggest the first, second or third byte. If 10 is entered it displays e.g. 101-109 if networks starting with those numbes exist. If "10." is enterd it shows e.g. 10.[101-109] for the second byte. If "10.101" it displays 10.101.[2-255] for the third byte. For the forth byte the whole net ( e.g. 10.101.243.64 ) ist listed.
I hope this is understandable, if not let me know.

May not be perfect right now but gives a good hint if the there is an existing net for the entered ip.
I will try IPv6 later, too.

**Comment by github138** [comment]
Make IP suggest more usable

**Comment by andriyanov** [comment]
It seems to me that this feature (IP suggest) must be configurable so a user could disable it. The SQL query seems quite ineffective, and some users do have very complicated address plans with thousands of IPv4 and many thousands of IPv6 networks.

Also, I believe you should only enable the suggestion if user already typed the first dot, indicating this is an IPv4 address. If the typed text contains ":" indicating this is an IPv6, suggest should stop responding (and maybe even stop requesting from JS).

Also, I'm still not sure if this feature is worthwhile at all. Does anybody remember his octet values to choose one of possible completions? And this feature does not help you at all to select the available last octet inside the network, which is the most valuable.

That's why I'm not going to accept the IP auto-complete feature. Could you please make a separate PR just for port names?

**Pull request closed without merging**
