### PR TITLE
enable CSS and JavaScript from external URLs

### PR DESCRIPTION
**Pull request by netniV**
This change allows the use of CDN-based scripts and CSS

### CODE REVIEW

**Comment by infrastation** [comment]
To spell the terms, what this change adds support for is an URL (URI is what is currently implemented).

Besides that, the existing `addCSS()` and `addJS()` functions have been designed a bit wrong but I never got to make them right, so this may be a good occasion. It seems to me, the following set of functions would result in cleaner code (mind the the uri/url difference):
```php
function addJSText ($text)
function addJSInternal ($uri)
function addJSExternal ($url)
function addCSSText ($text)
function addCSSInternal ($uri)
function addCSSExternal ($url)
```
Would you like to make that change a part of this pull request?

**Comment by netniV** [comment]
I can do.  Would you like the addJS() / addCSS() to try to determine which to call?

**Comment by netniV** [comment]
Btw, technically a URL is a URI, but a URI may not always be a URL 👍 
https://danielmiessler.com/study/url-uri/

**Comment by infrastation** [comment]
Excuse me if my terminology isn't perfect, but to speak the same language in the scope of this pull request let me say that an URL is handled by the user's browser without RackTablesy and an URI is passed to the "chrome" RackTables module, which will resolve it to one or another filesystem path depending on local configuration and presence of particular plugins.

Speaking about the PHP code changes, the existing functions should become:
```php
// DEPRECATED
function addCSS ($data, $inline = FALSE)
{
	if ($inline)
		addCSSText ($data);
	else
		addCSSInternal ($data);
}
```
(Slightly more complex for `addJS()` but along the same lines -- one function does one job and does it well.) This change requires the static variables replaced with globals.

**Comment by netniV** [comment]
Yes, that's clear 👍 

Would you want a warning logged about using a depreciated function?

**Comment by infrastation** [comment]
Thank you, that's definitely a step in the right direction but mind the code style please. Also some of the calls to the new functions still have a `TRUE` as the 2nd argument, which will feed the `$group` argument without intention. Also the new function `getMergedHeaderArray()` is not used anywhere. Also it would be simpler to initialize `$html_headers` and `$seen_headers` in `init.php` once rather than in each new function.

Would you like to fix these issues yourself before the merge?

**Comment by infrastation** [comment]
Forgot to add: where possible, please try to add tests for new functions.

**Comment by netniV** [comment]
Where do you normally add the tests? The `getMergedHeaderArray()` was from the first attempt, then I realised that was cumbersome and reworked it, just forgot to strip that back out.

**Comment by netniV** [comment]
I thought I had caught all the FALSE (since non should be using that now).

**Comment by infrastation** [comment]
In the commit 439c358 you can see how to test `isUrl()` and `isUri()` as these two functions are pure. The functions that modify global arrays are not pure and would require a custom class similar to what you find in `ConfigVarTest.php`. To run the tests you will need a mock RackTables instance in the database named `racktables_unittest` (take care not to use your production database for that as the contents will be damaged), then you run `./tests/express.sh` and watch -- it should work very similar to what happens in Travis CI automatically.

**Comment by netniV** [comment]
OK I will sort this out shortly.  I might get chance to look at the bug tracker thing tonight which I think will only occur when you skip a version (eg, from 0.21.0 to 0.21.2)

**Comment by netniV** [comment]
So I have now added unit tests, but also functionality to do a basic detection for empty database.  If the config table isn't present it now allows you to initialise the database without needing to keep changing / removing the secret.php file.

**Comment by infrastation** [comment]
Based on prior experience I thoroughly recommend to make unrelated changes in separate pull requests, especially that the points raised above still stand.

**Comment by netniV** [comment]
The other mods should be there now.

**Comment by infrastation** [comment]
Thank you. Could you confirm whether you are going to address the remaining points?

**Comment by netniV** [comment]
Remind me which are the remaining points, at this point I've got it in my head I'd done everything as everything appears to be working as requested.

**Comment by netniV** [comment]
I think I've caught everything.  If you are happy with the code, I'll attempt to seperate these things out.

**Comment by infrastation** [comment]
In `isUri()` it would make sense to use the existing `RE_STATIC_URI`. A number of other minor nits remains, I could probably fix these myself faster if you prefer, in either case these are not blockers. The unrelated changes to `init.php` and `install.php` currently block the merging, please sort that soonest.

**Comment by infrastation** [comment]
Also please include a line in `ChangeLog` and possibly a note about the deprecated functions in the release notes in `README.md` and `upgrade.php` if you think that would be useful.

**Comment by netniV** [comment]
OK, so I think we are there.  Well, aside from the things you can see that I keep missing ;-)

Going to be fun maintaining yet another coding style in my head and remembering which project is using what!  Most of the styling mistakes were from the style we use on the Cacti project which has been drummed into me before I even became a full developer of it.

Not sure if the documentation is as you'd like, but I did a verbose version in the README.md and a terse version in the upgrade.php.

**Comment by infrastation** [comment]
Thank you, the text in `README.md` is the last entry in the versions list (should be the first), I will check other changes later.

**Comment by infrastation** [comment]
To follow up on one of your earlier comments, I have updated the code style for the currently supported PHP versions, thank you for pointing that out.

**Comment by netniV** [comment]
Corrected that mistake with README.md

**Comment by infrastation** [comment]
Nope, the delay is with me, excuse me.

**Comment by netniV** [comment]
No worries, just wanted to be sure :)

**Comment by infrastation** [comment]
Thank you for making this contribution, subsequent commit fixes some remaining minor issues, so this is considered done and ready.

**Pull request merged**
