### PR TITLE
Add support for UCS vnic port discovery

### PR DESCRIPTION
**Pull request by bpothier**
(more details in the individual commit entries)
modifies:
gateways/ucssdk
wwwroot/inc/ophandlers.php
Brian

### CODE REVIEW

**Comment by bpothier** [comment]
This is my first contribution, do I need to create a Mantis case as well?
I saw a Mantis the mentioned code contribution and the response was to create a pull request, so that is the approach I took....
Brian

**Comment by infrastation** [comment]
Brian, everybody is a bit backlogged or on holidays. I will try to look into this after resolving another pull request I am already looking into.

**Comment by phgrau** [comment]
This is a very nice patch. 
I've added additional support for UCS managed rackmount server in pull  request #136.
 
I would change the regexs that handle the names of the vnic ports. Since the DN can have a structure of 

```
DN = {rn}/{rn}/{rn}/{rn}...
``` 
See http://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/sw/api/b_ucs_api_book/b_ucs_api_book_chapter_00.html#c_objectnaming

so my regex in lines 3382 and 3383 in `ophandlers.php` would look like
```
$spname = preg_replace ('#^(.+)/ls-([^/]+)/([^/]+)$#', '${2}', $item['DN']) . "(" . $oinfo['name'] 
$porttype = preg_replace ('#^(.+)/([^-/]+)-.+$#', '${2}', $item['DN']);
```
And my pull request needs the `$spname_id[$spname] = $new_object_id = commitAddObject ($spname, NULL, 4, NULL);`

regards.

**Comment by infrastation** [comment]
Upon reading through this new code it looks fine style-wise; so long as you seem to have exposure to UCS I am OK to merge this pull request as it is. Please let me know if you intend any late changes to it.

Exactly the same applies to pull request #136 .

**Comment by bpothier** [comment]
I tried to match the existing style and minimize the diff entries to make your merge easier. :)

have not looked at 136 yet, we do have rack servers in our other lab I could test it on next week. 

my only correction would be to somehow remove the "default" port entries - eth0,kvm,etc... - that creating the new server entry adds. I'm not quite familiar enough with your code to figure it out yet...
also, in future I'd like to add some sort of "refresh" option that doesn't require running the cleanup, as that removes all rack location information... you shouldn't need to redo all the location settings just to update some profile info...
Brian

**Comment by phgrau** [comment]
I currently have no further objections. I would greatly welcome an refresh option in the future. 

So the merge of #131 and #136 with my annotation would be great. And don't mind,
I would resubmit if something gets lost...

Kind regards.

**Comment by infrastation** [comment]
Thank you! Please rebase any future changes on the then-present maintenance-0.20.x branch.

**Pull request merged**
