### PR TITLE
Add all SuperMicro chassis and servers

### PR DESCRIPTION
**Pull request by Miouge1**
This is a follow up on #200 it includes all SuperMicro servers and chassis (product names starting by SYS- and SSG-) published on supermicro.com

### CODE REVIEW

**Comment by infrastation** [comment]
That is a lot of new entries, do all of them stand for different products and not variations like amount of pre-installed memory, CPUs and such? As a rule of thumb, any entry in `dictionary.php` should not be possible to obtain from any other entry plus or minus spare parts and components.

**Comment by Miouge1** [comment]
All entries exclude the amount of RAM and the CPU model, but are different config in term of:
- storage bays (example: 2028R-E1CR48L vs 2028R-E1CR24L)
- different storage controllers (example: 2028R-E1CR48L vs 2028R-E1CR48N)
- On-board network  (2028TP-HC1FR vs 2028TP-HC1TR)

For reference the SuperMicro product naming convention is available here: https://www.supermicro.com/products/Product_Naming_Convention/Naming_SYS_25.cfm

Aside maybe from the external storage controllers (example 2) I think it should be compatible with the rule of thumb?

**Comment by infrastation** [comment]
Thank you for the explanation, based on this I can comment as follows:

* 2028R-E1CR48L and 2028R-E1CR24L should be different entries in the dictionary because the chassis are mechanically different and the motherboards are different. Those cannot be converted to each other.
* 2028R-E1CR48L and 2028R-E1CR48N use the same chassis and motherboard, the controller in 2028R-E1CR48L is an add-on card hence there should be only one 2028R-E1CR48N entry (or possibly E1CR48x if that fits SuperMicro naming system).
* 2028TP-HC1FR and 2028TP-HC1TR have different motherboards hence should be different entries.

Also it may help to split the new entries into groups like "SuperMicro 1U", "SuperMicro 2U" etc. What do you think?

**Comment by Miouge1** [comment]
Sounds reasonable, I made the GPASS for SuperMicro 1U 2U etc...
I also removed things like the E200-8B.

**Comment by infrastation** [comment]
Thank you for your contribution, this data is now in the master branch.

**Pull request merged**
