### PR TITLE
doSNMPmining refactoring

### PR DESCRIPTION
**Pull request by xornet-sl**

### CODE REVIEW

**Comment by infrastation** [comment]
An attempt to reuse a valid MAC address on another object must fail and throw and exception, the first two commits seem to break this semantics if I understand it right.

**Comment by xornet-sl** [comment]
No. In the first commit there are also two database triggers for table Port.
These triggers will call undefined procedure if the check will fail.
Calling an undefined procedure in before-insert/update trigger leads to PDO exception with meaningful text.

**Comment by andriyanov** [comment]
Please add a unit-test to confirm the L2 address uniqueness logic still works.
Also, a release note requiring MySQL >= 5.0 should be added into README and upgrade.php files.
Pre-upgrade check for MySQL version would be also nice thing to have.

Besides that, the commit looks good to me.

**Comment by andriyanov** [comment]
Thank you!

**Comment by infrastation** [comment]
There are two issues with this change. First and most obvious, it changes the exception class so that it is no more `InvalidRequestArgException` or `InvalidArgException`, the consequence is on invalid user input RackTables now prints a PDO exception and stops (as PDO exceptions are considered fatal by default). Second, this changeset does not explain what problem it solves and how the solution is intended to work, so it takes to read through all the changes to guess. Can you review?

**Comment by infrastation** [comment]
Would you like to fix it or would you like to revert the changes?

**Comment by xornet-sl** [comment]
I will fix it today

**Pull request merged**
