### PR TITLE
Added extra hooks to commitUpdateObject()

### PR DESCRIPTION
**Pull request by jeroenvermeulen**
Added extra hooks to commitUpdateObject() to give plugin devs more options to interact.

### CODE REVIEW

**Comment by jeroenvermeulen** [comment]
Usage example:
In `plugins/demo.php`

	<?php

	registerHook ('commitUpdateObjectAfter_hook', 'demo_commitUpdateObjectAfter_hook');

	function demo_commitUpdateObjectAfter_hook ($object_id)
	{
		static $in_function;
		if ($in_function) 
		{
			return; // Prevent endless recursion
		}
		$in_function = true;
		$object = &spotEntity('object', $object_id);
		if 
		(
			4 == $object['objtype_id'] &&  // 4 = Server
			!empty ($object['name'])
		)  
		{
			if ( empty($attrs[3]['value']) )  // 3 = FQDN
			{  
				commitUpdateAttrValue
				(
					$object_id, 
					3, 
					strtolower($object['name']).'.example.com'
				);
			}
			if ( empty($object['asset_no']) ) 
			{
				$object['asset_no'] = $object['name'];
				commitUpdateObject  // Recursion
				(
					$object['id'],
					$object['name'],
					$object['label'],
					$object['has_problems'],
					$object['asset_no'],
					$object['comment']
				);
			}
		}
		$in_function = false;
	}

**Comment by infrastation** [comment]
Thank you, feel free to contribute this snippet to the racktables-contribs repository.

**Comment by jeroenvermeulen** [comment]
Maybe it's better to do that after a new release is drawn, because in 0.20.13 this won't work.

**Comment by infrastation** [comment]
OK, RackTables 0.20.14 will have this commit too so you can put a comment with the version requirement at the file top if you want.

**Pull request merged**
