### PR TITLE
add has_problems auto tag

### PR DESCRIPTION
**Pull request by github138**

### CODE REVIEW

**Comment by infrastation** [comment]
This would be the simplest solution (though `findAutoTagWarnings()` would have to be updated as well) but in long term it is not good because `Object.has_problems` column is a legacy. If you have the time to implement a better design I can explain it.

**Comment by github138** [comment]
hopefully correctly updated findAutoTagWarnings().

Not sure i have the time but could you explain the better design?

**Comment by infrastation** [comment]
There was the most recent attempt to explain it: http://comments.gmane.org/gmane.comp.misc.racktables.user/3867

The hue-saturation-value representation of the colours of interest is as follows:
* 180-50-50 stands for an unselected object with has_problems=no
* 180-50-100 stands for a selected object with has_problems=no
* 0-50-50 stands for an unselected object with has_problems=yes
* 0-50-100 stand for a selected object with has_problems=yes

You can see the object cursor increases the V component of the HSV colour model whilst the other two remain the same. The proper solution would be to make this base colour an optional property of the tags and to deliver it either inline or through a CSS file. The first revision may implement just a selection of, for instance, 32 colours rather than a custom RGB value to make it more easy to implement.

In a system implemented this way there would be no "has problems" checkbox anymore. The user would have a tag with the colour of interest and assign it to required objects. There would be no problem accessing the tag from RackCode and it would be possible to represent more than one type of problem and to represent more than one severity level (e.g. orange for warning, red for error).

Hopefully it is not too complicated.

**Comment by github138** [comment]
What should happen if an object has two or more tags with color?

**Comment by infrastation** [comment]
Good point. How would you solve this?

**Comment by github138** [comment]
I hoped someone else could answer this.
At the moment i am playing with linear-gradients.

**Comment by infrastation** [comment]
One way could be to have a priority field but this starts looking overly complicated. Maybe the whole idea of storing the colour in the database is wrong. Instead there could be a function that would take an entity record as input, made necessary calls to `considerGivenConstraint()` (or any other checks) and returned the colour(s) to use. This would have to be an optional user-defined function. What do you think?

**Comment by github138** [comment]
I have a test version with colored tags. Should i open a new request or do you want a patch?
It's still quite experimental.
-setting colors over the config page works
-multiple colors per object with sharp linear-gradients
-colors on objects page and rack diagram ( not miniracks)

**Comment by infrastation** [comment]
Would be nice to see a screen shot (in racktables-users if you would like more early feedback).

**Comment by infrastation** [comment]
In your ptototype does the colour change as the object on the diagram becomes the current object?

**Comment by github138** [comment]
Yes, it is displayed with a colored border
coloredtag

**Comment by infrastation** [comment]
Could you make sure your new code complies with the [code style guide](https://wiki.racktables.org/index.php/SourceCode) and open a pull request?
If it works well enough to be merged now and improved later based on the users feedback, I would not want to delay it unnecessarily.

**Comment by infrastation** [comment]
Closing, replaced by #158.

**Pull request closed without merging**
