### PR TITLE
 workaround ?logout urls relogin problem fixes

### PR DESCRIPTION
**Pull request by github138**
workaround ?logout urls relogin problem

```
see http://bugs.racktables.org/view.php?id=1309
```

### CODE REVIEW

**Comment by infrastation** [comment]
The code that authenticates users is an important part of the software. When making changes to it, please explain both the problem and the solution in the commit message.

**Comment by github138** [comment]
This would be a fix for Request #104. Which should corret the relogin behaviour. After logout you have to change the URL ( remove ?logout ) to login in again.
The intension was to user a SESSION variable to solve this.
This (#105) should fix that you have to login twice with #104 applied.

**Comment by github138** [comment]
see request #107 for different solution

**Comment by github138** [comment]
Logout URL was not always working

**Comment by mltmtncr** [comment]
after logout when i click the back button session is continiue running how can i fix that problem

**Comment by github138** [comment]
You could try #107 which address this kind of issue

Also see
http://stackoverflow.com/questions/449788/http-authentication-logout-via-php

**Comment by infrastation** [comment]
Replaced by pull request #107, closing this one.

**Pull request closed without merging**
