### PR TITLE
Updated getImageHREF to allow base64 data to be used

### PR DESCRIPTION
**Pull request by Breloc**
This patch add the ability to embed images in base64.

### Why I believe this could be useful
As I'm finishing the implementation of a plugin with the new plugin architecture, I'm trying to achieve a setup avoiding to copy files in `wwwroot` subfolders `css`, `js` and `pix`. The goal is to keep plugin setup as simple as possible, and avoiding the need to copy files that will probably stay forever after plugin uninstall.

For CSS and JS ressources, I had no problem thanks to `addJSInternal()` and `addCSSInternal()` methods, but for the main page icon `$image['pluginname']['path']`, I didn't found any other workaround than embedding icon in base64.

Best regards,
Breloc

### CODE REVIEW

**Comment by infrastation** [comment]
Thank you for preparing this change. Indeed there is such a place for improvement, but the solution would need to be a bit cleaner. Would you prefer to prepare it after my description, or to let me make it?

**Comment by Breloc** [comment]
Thanks for your fast reply !
I'll wait for your description and work on it

**Comment by Breloc** [comment]
Thanks for these very clear explanations. Let me know if you'd like some other changes in this new commit, or if it's good enough to be merged

**Comment by infrastation** [comment]
Thank you for preparing the next revision. Looking at the resulting code, it is possible to make a couple more improvements, but for sake of unblocking your work I can make these afterwards. Does the proposed change as it is solve the problem for your plugin code?

**Comment by Breloc** [comment]
Great, thanks for your help. 
Yes, the problem is solved, and I'll submit my plugin on contrib repo very soon

**Comment by infrastation** [comment]
Done, thank you.

**Pull request merged**
