### PR TITLE
Patch to get basic SSL support

### PR DESCRIPTION
**Pull request by stephengroat**
Requires mods to secret.php, not integrated into gui.

Should be an OK start, can add to documentation.

(Would be great if the documentation & bug tracking were integrated into github :) )

Signed-off-by: sgroat <stephen@egroat.com>

### CODE REVIEW

**Comment by adummer-nodeprime** [comment]
Please add some documentation and sample values to secret.php (see the init_config function in install.php).

**Comment by adoom42** [comment]
Please add some documentation and sample values to secret.php (see the init_config function in install.php).

**Comment by infrastation** [comment]
OK except the slashes in the paths would be the forward ones for most users.

**Comment by infrastation** [comment]
Would you like to spell your author line consistently in both commits?

**Comment by stephengroat** [comment]
Fixed the paths. I've had a few installs switch to using the hack and it seems to work just fine for about a week.

Don't know have to fix the author line issue, if you can let me know how to do I can go back and edit it

**Comment by infrastation** [comment]
Commit 2778b35 is a squashed version of this, thank you!

**Pull request closed without merging**
