### PR TITLE
Update interface.php for accesskey <alt>+<s>

### PR DESCRIPTION
**Pull request by LeroyZwakman**
Added a accesskey property to the input tag. This makes the searchbox focus when you press < alt > + < s > for easier / faster searching.

### CODE REVIEW

**Comment by infrastation** [comment]
This commit does not need to change whitespace.

**Comment by LeroyZwakman** [comment]
Sorry for the whitespace fault.
I've corrected the whitespace.

**Comment by infrastation** [comment]
Thank you.

**Comment by LeroyZwakman** [comment]
Awesome, thank you!

**Pull request merged**
