### PR TITLE
fix PDO Exception for mysql 5.7 for ONLY_FULL_GROUP_BY

### PR DESCRIPTION
**Pull request by github138**
* getRowInfo: add Location.id to GROUP BY
* remove workaround 0c53bc48808489b4ee1f7cda725aebe121713385

### CODE REVIEW

**Comment by infrastation** [comment]
So this is the proper fix for Mantis #1635, right?

**Comment by github138** [comment]
Well, i'm no SQL expert. But that how i understand it.

**Comment by infrastation** [comment]
Fine. Tomorrow morning I am expecting to have this tested and merged.

**Comment by github138** [comment]
I think i got the right solution now. We don't need the GROUP BY at all, because the WHERE clause only selects one row.id. So no need to GROUP by row.id then. 
Do you agree?

**Comment by infrastation** [comment]
If your previous comment still stand, then `GROUP BY` is required by `COUNT()` and `SUM()`. That said, it may be possible to rewrite the query without `JOIN` and without `GROUP BY` if the related information about the racks and the location come from sub-selects.

**Comment by github138** [comment]
I saw the COUNT() afterwards, too. Sorry for the noise.
Not sure if the sub-selects version is easier to understand.
GROUP BY row.id and location.id seems ok, since there is only one location.id per row, right?

**Comment by infrastation** [comment]
Yes, there should be only one.

**Comment by infrastation** [comment]
Or __at most__ one, as a row can have no location.

**Comment by infrastation** [comment]
Please let me know once you are sure this is the final version of the fix.

**Comment by github138** [comment]
Yes, this is the final fix.

**Comment by infrastation** [comment]
Thank you. The tests now include a call to the changed function.

**Pull request merged**
