### PR TITLE
add alternating tables rows to IPSpace

### PR DESCRIPTION
**Pull request by github138**

### CODE REVIEW

**Comment by infrastation** [comment]
Have you considered using a style like it is done in commit 3b15479?

**Comment by github138** [comment]
Looked at the wrong place. Changed to use "zebra" css class.

**Comment by infrastation** [comment]
Merged, please see a couple follow-up commits I made after testing on my PC. Thank you!

**Comment by infrastation** [comment]
There is an issue introduced in this change: the `trbusy` CSS class currently has no effect on the address list printed in `renderIPv4NetworkAddresses()` and `renderIPv6NetworkAddresses()`. It seems to me the `zebra` style tends to enhance the tables that had no style before, but for tables that were already using some colour markup the additional style may not work well.

It cannot be left as it is now because it makes impossible to tell reserved addresses and difficult to tell allocated addresses on the list. Do you think it would be better to change those two functions as they were before or use some other solution?

**Comment by github138** [comment]
It is because the zebra style applies at last, so anything else is below that. Same issue with tag colors.
I have added "!important" to the highlight styles which works around that.Alternating colors are then below the highlight color. With transparent highlight color even the alternating lines are visible ( see c789a80 ).
Another solution could be to exclude those in the zebra class. E.g. add a extra class "nozebra" and add :not('nozebra')  to the zebra class. But then there is no alternating if multiple lines have the same classes applied.

**Comment by infrastation** [comment]
So long as there is no good solution, let's not have the problem.

**Pull request merged**
