### PR TITLE
Pluggable authentication methods

### PR DESCRIPTION
**Pull request by xornet-sl**
This approach allows us to add some custom Auth providers to Racktables.
What do you think about it, guys?

### CODE REVIEW

**Comment by xornet-sl** [comment]
Why does the check fail? definition of $racktables_plugins_dir and $racktables_rootdir variables is in pre-init.php, which loads before auth.php

**Comment by infrastation** [comment]
A single line comment for such an intrusive change is less than enough I am afraid. And the checks must pass, of course.

**Comment by xornet-sl** [comment]
Of course, I will rework this commit. I just decided to show it and read some crit.

**Comment by xornet-sl** [comment]
I've added some comments in auth.php and changed commit message. Please, check it.

**Comment by xornet-sl** [comment]
@infrastation Denis, it would be great if you could look at this merge request. Do I need to fix something more or you just don't like this approach?

**Comment by infrastation** [comment]
Just busy.

**Comment by splattner** [comment]
:+1:

**Comment by infrastation** [comment]
This door is no longer open.

**Pull request closed without merging**
