### PR TITLE
Fix for warning when adding a new page via registerTabHandler() in plugin

### PR DESCRIPTION
**Pull request by jeroenvermeulen**
Fix for warning when adding a new page via registerTabHandler() in plugin:

    PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in .../wwwroot/inc/functions.php on line 495

### CODE REVIEW

**Comment by jeroenvermeulen** [comment]
Travis died saying

    ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

I don't think that's my fault.

**Comment by infrastation** [comment]
The build failure is Travis-specific, they said it should resolve in 1-2 days. I have briefly looked through the change to see it requires more thorough reading so let me update later.

**Comment by infrastation** [comment]
The commit renames `$page` to `$pageno` and then makes the following change:
``` diff
--- a/wwwroot/inc/functions.php
+++ b/wwwroot/inc/functions.php
@@ -5934,6 +5934,10 @@ function registerTabHandler ($pageno, $tab, $callback, $method = 'after')
 {
        global $tabhandlers_stack;
        global $tabhandler;
+       global $page;
+
+       if (! isset ($page[$pageno]))
+               $page[$pageno] = array();
 
        if (! isset ($tabhandlers_stack[$pageno][$tab]))
                $tabhandlers_stack[$pageno][$tab] = array();
```
Could you explain the use case of the original problem? It is difficult to understand how this change is a solution and why it needs to be done in this function. Thank you.

**Comment by jeroenvermeulen** [comment]
One of our plugins adds a page called `api`.
The functionality is accessible via the URL:
https://racktables.domain.ext/index.php?page=api&tab=ip&op=mhGetDomainIp 
```
<?php
registerTabHandler ('api', 'ip', 'mhGetDomainIp', 'before');

function mhGetDomainIp($bypass = null)
{
...
}
```

When I access the URL, these errors are logged:
```
[01-Aug-2017 14:40:34 UTC] PHP Notice:  Undefined index: api in /data/ssd/vhosts/racktables.magehost.pro/racktables/wwwroot/inc/functions.php on line 495
[01-Aug-2017 14:40:34 UTC] PHP Stack trace:
[01-Aug-2017 14:40:34 UTC] PHP   1. {main}() /data/ssd/vhosts/racktables.magehost.pro/racktables/wwwroot/index.php:0
[01-Aug-2017 14:40:34 UTC] PHP   2. getBypassValue() /data/ssd/vhosts/racktables.magehost.pro/racktables/wwwroot/index.php:35
[01-Aug-2017 14:40:34 UTC] PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /data/ssd/vhosts/racktables.magehost.pro/racktables/wwwroot/inc/functions.php on line 495
[01-Aug-2017 14:40:34 UTC] PHP Stack trace:
[01-Aug-2017 14:40:34 UTC] PHP   1. {main}() /data/ssd/vhosts/racktables.magehost.pro/racktables/wwwroot/index.php:0
[01-Aug-2017 14:40:34 UTC] PHP   2. getBypassValue() /data/ssd/vhosts/racktables.magehost.pro/racktables/wwwroot/index.php:35
[01-Aug-2017 14:40:34 UTC] PHP   3. array_key_exists() /data/ssd/vhosts/racktables.magehost.pro/racktables/wwwroot/inc/functions.php:495
```

**Comment by infrastation** [comment]
Is the plugin intended to be a part of the user interface or is it for scripting/automation?

**Comment by jeroenvermeulen** [comment]
We are POSTing data to this URL from a script in Google Sheets.
It sends and receives JSON data.
So not a user interface directly intended for humans.

**Comment by infrastation** [comment]
In this case the plugin should register itself differently:
``` php
<?php

# index.php?module=ajax&ac=mhAPI&function=getDomainIP

$ajaxhandler['mhAPI'] = 'mhAPIDispatcher';

function mhAPIDispatcher()
{
  switch (genericAssertion ('function', 'string'))
  {
  case 'getDomainIP':
    echo json_encode (array ('result' => 'mydata'));
    break;
  default:
    echo "NAK\nunknown function";
  }
}
```

**Comment by jeroenvermeulen** [comment]
OK Thank you, will use that.
But I think my PR is an improvement not causing any harm at all.

**Comment by infrastation** [comment]
In the situations when a plugin is trying to register itself at navigation nodes that do not exist any error messages are a feature and not a bug. In `registerTabHandler()` and `registerOpHandler()` it would be more correct to throw an exception, feel free to open another pull request if you would like to implement this.

**Pull request closed without merging**
