### PR TITLE
Add 'live ports' support for fdry5 as well as support Brocade FCX 648 and FLS 648 

### PR DESCRIPTION
**Pull request by etcet**
- Add getportlist, getmaclist, getportmaclist for fdry5.
- Use fdry5 breed for Brocade FastIron CX 648 and Brocade FastIron LS 648.
- Allow sshnokey to use $tolerate_remote_errors.
- Add $hide_warnings flag to hide the 'Connection to x.x.x.x closed by remote host.' error on exit when using ssh or sshnokey with fdry5.

### CODE REVIEW

**Comment by infrastation** [comment]
I have read through the changes, most are obviously safe but the small changes in `queryTerminal()`, which would welcome an extra pair of eyes.

**Comment by etcet** [comment]
Thanks for the review. I considered separating this into two requests but decided against it as the live ports page for Foundry/Brocade won't work without it. 

I work with a few pieces of their hardware from the core to the edge and they all exhibit the same behavior: when you disconnect a ssh session it exits with 'Connection to x.x.x.x closed by remote host'. Without my changes, even though we can got port and mac address data, an error did technically occur and the 'list ports' page will not show any data - just the error. With $tolerate_remote_errors we can still see the data but there will always be an error in bright red at the top, hence $hide_warnings.

The other change from $settings['protocol'] to substr($settings['protocol'],0,3) is so that 'sshnokey' can also tolerate errors like 'ssh' can.

**Comment by andriyanov** [comment]
Chris, do you experience this error message problem only with Brocade devices? I suspect it might me a generic problem and should be fixed another way.

**Comment by etcet** [comment]
I do only experience the error upon disconnect issue with Brocade devices.

**Comment by andriyanov** [comment]
Merged, thank you!

**Pull request merged**
