### PR TITLE
Master

### PR DESCRIPTION
**Pull request by xornet-sl**

### CODE REVIEW

**Comment by infrastation** [comment]
It would be wrong to suppress warnings in `array_fetch()`, if it makes a problem visible the problem should be fixed (or, if `array_fetch()` is not the right function, that particular change reverted). I will check it.

**Comment by infrastation** [comment]
Regardless of commit 07d22ce and the proposed change, with `$name_in_value == TRUE` any element of `$plist` that is not an array or does not have the key 'name' will produce a PHP warning. At the same time, `array_fetch()` only produces a warning when the argument is not an array. This way the problem you are describing in the commit message has existed for a long time or I failed to follow the text. What do the warning(s) say?

**Comment by infrastation** [comment]
The first commit from this pull request has been cherry-picked into the master branch.

**Comment by xornet-sl** [comment]
No, the construction like `isset($plist[$pkey]['iif_id']) ? $plist[$pkey]['iif_id'] : 0` never produces any warnings, but `array_fetch ($pvalue, 'iif_id', 0)` does. You can reproduce it on any `index.php?page=vlan&vlan_ck=` vlan info page with `error_reporting (E_ALL)`. You will see a huge amount of warnings in "Switch ports" portlet. I think we should suppress the warnings like these ones, shouldn't we? Especially it makes sense on debug instances.
Warnings say: `Warning: array_key_exists() expects parameter 2 to be array, integer given in ...../wwwroot/inc/functions.php on line 5837` in context of `renderVLANInfo -> usort_portlist -> sortPortList`. usort_portlist constructs $plist arg of sortPortList as array of integers on which array_fetch throws warnings, but isset() didn't.

**Comment by infrastation** [comment]
The bug was in `usort_portlist()` and it has been fixed in the master branch, thank you for the detailed report. Closing.

**Pull request closed without merging**
