### PR TITLE
add FreeBSD 10 README Notes

### PR DESCRIPTION
**Pull request by github138**

### CODE REVIEW

**Comment by github138** [comment]
Where could i put additional install instructions for FreeBSD?

**Comment by infrastation** [comment]
Use something like "see note below" and a follow-up subsection further down. Please try to keep the tables sorted by the 1st column.

**Comment by github138** [comment]
Added more complete install notes for FreeBSD

**Comment by infrastation** [comment]
Is this the final version?

**Comment by github138** [comment]
Made one small final change.
Maybe i extent it later with notes on how to use RT with nginx on FreeBSD.

**Comment by infrastation** [comment]
OK, maybe eventually some of this information will land in wiki, we shall see. I am squashing this into one commit for brevity.

**Comment by infrastation** [comment]
Thank you!

**Pull request merged**
