### PR TITLE
allow allocation of ip address only once

### PR DESCRIPTION
**Pull request by github138**
Do not allow to allocate a non shared IP twice

### CODE REVIEW

**Comment by github138** [comment]
Add Warning on allocation of reserved IP addresses

**Comment by andriyanov** [comment]
I believe that someone wants to keep the existing ability to assign one IP to multiple objects. After all, multiply allocated IPs are highlighted red.

Do you have a reason to push that in upstream instead of making a plug-in?

**Comment by github138** [comment]
But it is only red in the IP Space Page. If i allocate an IP over the object page everything ist green (added a record successfully).
Isn't this the meaning of the IP types. Shared ones can still be allocated to multiple objects.
For IP Management it would be realy nice to know which IP is already used / reserved.
Not sure if a plugin could catch that.

**Comment by andriyanov** [comment]
Green color means highlighted. Normally when you open an object's page, re-used non-shared IP allocations would be red.

**Comment by github138** [comment]
ok. So the green highlight overlays the red warning. At least there should be a warning if a ip is assigned a second time. At the moment i only get a green success message. ( "added a record successfully" ) with the highlighted green ip address.

**Comment by andriyanov** [comment]
Displaying a warning looks OK for me. Could you please submit the patch that removes the 'return' statement?

**Comment by github138** [comment]
Updated the pull request

**Comment by andriyanov** [comment]
Merged, thank you!

**Pull request merged**
