### PR TITLE
This is a single image of the graphical relationship of the parts of

### PR DESCRIPTION
**Pull request by MichaelTiernan**
the schema used in RackTables. I've been looking for how certain
things link together and I used this to help me.
I created it using the MySQL Workbench tool.

### CODE REVIEW

**Comment by infrastation** [comment]
That's remarkable. It would fit nicely in the "figures" directory of the racktables-contribs repository.

**Comment by infrastation** [comment]
Would you like to open a new pull request or would you like me to commit the image as mentioned above on your behalf?

**Comment by MichaelTiernan** [comment]
If you'd be willing to do it that'd be better simply since I'm still so
green with the processs.

Thank you very much.

-- 
    << MCT >>   Michael C Tiernan.    http://www.linkedin.com/in/mtiernan

    Non Impediti Ratione Cogatationis
    Women and cats will do as they please, and
    men and dogs should relax and get used to the idea. -Robert A. Heinlein
    Sorry for the unedited top post. Client forces it.

**Comment by infrastation** [comment]
Done -- it is in racktables-contribs now, thank you!

**Pull request closed without merging**
