### PR TITLE
Add htmlentites for value when transformrequest

### PR DESCRIPTION
**Pull request by qhess34**

### CODE REVIEW

**Comment by qhess34** [comment]
This change is related to a bug :
When you add a quote in a custom attribute value, the part of the string after the quote is not included into the input value when editing.

**Comment by infrastation** [comment]
Thank you for proposing this improvement. As far as I can tell, the problem does not reproduce on the latest stable version, is this correct? If it does, could you add specific steps to reproduce please?

The main issue with the proposed change is that it effectively makes `$sic == $REQUEST`, which would break plenty of code downstream. So if there is a problem, the solution would need to be different.

**Comment by qhess34** [comment]
I just tried on the 0.21.5 and the bug is still present.
To reproduce :
- Edit an object with at least one custom attribute with type string
- On the attribute value insert the string "PartA'PartB"
- Submit the form
- After the page refresh, the bug appears on the input of the just modified attribue : 
`<input type="text" name="3_value" value="PartA" partb'="" tabindex="1">`

**Comment by infrastation** [comment]
Yes, you are right, it is the single quote that triggers it. Let me see how to fix it properly.

**Comment by infrastation** [comment]
See commit ff197ea. The bug fix will be available in RackTables 0.22.0 or 0.21.6, whichever comes out first. Thank you for reporting the issue, in future please use bugs.racktables.org for bug reports.

**Pull request closed without merging**
